config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: "owners", controllers: {
    sesions: "owners/sessions",
    registrations: "owners/registrations",
    passwords: "owners/passwords",
    confirmations: "owners/confirmations",
    unlocks: "owner/unlocks"
  }

  devise_for :users, path: "users", controllers: {
    sesions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  root "home#index"
  get "logins", to: "home#logins"
  get "minha_pousada", to: "inns#my_inn", as: "my_inn"
  get "minhas_reservas", to: "bookings#my_bookings", as: "my_bookings"

  resources :addresses, only: [:new, :create]

  resources :inns, only: [:new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    get "search", on: :collection
    get "city_search", on: :collection
    get "advanced_search", on: :collection
    delete "remove_photo", on: :member

    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:index, :new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    delete "remove_photo", on: :member

    resources :seasonal_prices, only: [:new, :create]

    resources :bookings, only: [:new, :create] do
      get "confirmation", on: :collection
      post "cancel", on: :member
      post "check_in", on: :member
      post "check_out", on: :member
    end
  end

  resources :bookings, only: [:index, :show] do
    get "active", on: :collection

    resources :reviews, only: [:new, :create] do
      post "answer", on: :member
    end
  end

  resources :seasonal_prices, only: [:show, :edit, :update, :destroy]

  resources :reviews, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get "cities", on: :collection
      end

      resources :bookings, only: [] do
        get "pre-booking", on: :collection
      end
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user, optional: true
  has_one :review
  has_many :booking_guests
  has_many :guests, through: :booking_guests

  validates :start_date, :end_date, :number_of_guests, presence: true
  validates :number_of_guests, numericality: {greater_than: 0}
  validates :code, uniqueness: true

  validate :check_in_overcrowd
  validate :past_dates, :date_conflict, :too_many_guests, :active_room, on: :create

  before_validation :generate_code, on: :create

  enum status: {confirmed: 0, active: 10, closed: 20, canceled: 30}

  def cancel_date
    start_date - 7.days
  end

  def calculate_bill
    return get_booking_range.reduce(0) do |bill, date|
      if room.seasonal_prices.any? { |price| date.between?(price.start, price.end) }
        room.seasonal_prices.each do |price|
          bill += price.price if date.between?(price.start, price.end)
        end
      else
        bill += room.price
      end
      bill
    end
  end

  private

  def get_booking_range
    return checkout_range if check_out
    start_date...end_date
  end

  def checkout_range
    limit = room.inn.check_out_time
    if check_out.hour >= limit.hour || (check_out.hour == limit.hour) && check_out.min >= limit.min
      start_date..check_out.to_date
    else
      start_date...check_out.to_date
    end
  end

  def date_conflict
    return if start_date.nil? || end_date.nil?

    conflict = room.bookings
                   .where(status: [:confirmed, :active])
                   .where.not(id: self.id)
                   .any? do |booking|
      (start_date..end_date).overlaps?(booking.start_date..booking.end_date)
    end

    errors.add(:date_conflict, I18n.t("date_conflict")) if conflict
  end

  def too_many_guests
    return if number_of_guests.nil?

    errors.add(:number_of_guests, I18n.t("too_many_guests")) if number_of_guests > room.max_guests
  end

  def past_dates
    return if start_date.nil? || end_date.nil?

    errors.add(:start_date, I18n.t("cant_be_past")) if start_date < Date.today
    errors.add(:end_date, I18n.t("cant_be_past")) if end_date < Date.today
    errors.add(:end_date, I18n.t("cant_be_before_checkin")) if end_date < start_date
  end

  def active_room
    room = Room.find_by(id: room_id)

    errors.add(:room, I18n.t("room_unavailable")) unless room&.active?
  end

  def generate_code
    self.code ||= SecureRandom.alphanumeric(8).upcase
  end

  def check_in_overcrowd
    return if guests.empty?

    # debugger

    if guests.length > number_of_guests
      errors.add(:guests, "Número de hóspedes maior que o informado na reserva")
    end
  end
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < Api::V1::ApiController
  def pre_booking
    pre_booking = Booking.new(pre_booking_params)

    if pre_booking.valid?
      render status: 200, json: {"valor": pre_booking.calculate_bill.to_f}
    else
      render status: 409, json: {"erro": pre_booking.errors.full_messages}
    end
  end

  private

  def pre_booking_params
    params.permit(
      :room_id,
      :start_date,
      :end_date,
      :number_of_guests
    )
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:my_bookings, :create]
  before_action :authenticate_owner!, only: [:index, :check_in, :check_out, :active]
  before_action :authenticate_user_or_owner, only: [:show, :cancel]
  before_action :set_booking, only: [:show, :cancel, :check_in, :check_out]
  before_action :set_room, only: [:new, :create, :confirmation]
  before_action :set_inn, only: [:new, :confirmation]
  before_action -> { authorize_access(@booking) }, only: [:show, :check_out, :check_in, :cancel]

  def index
    @inn = current_owner.inn
    @bookings = @inn.bookings.order(:start_date)
  end

  def new
    @pre_booking = Booking.new
  end

  def confirmation
    @pre_booking = Booking.new

    if session["pre_booking"]
      @pre_booking.assign_attributes(session_params)
    else
      @pre_booking = Booking.new(pre_booking_params)
    end

    if @pre_booking.valid?
      session["pre_booking"] ||= pre_booking_params
    else
      render "new"
    end
  end

  def create
    @booking = @room.bookings.build()

    if session["pre_booking"]
      @booking.assign_attributes(session_params)
    end

    @booking.user = current_user

    if @booking.save
      session.delete("pre_booking")
      redirect_to booking_path(@booking), notice: "Reserva confirmada"
    else
      render "confirmation"
    end
  end

  def show
    @room = @booking.room
    @inn = @room.inn
    @review = @booking.review
  end

  def my_bookings
    @bookings = current_user.bookings.where.not(status: :closed)
    @closed_bookings = current_user.bookings.where(status: :closed)
  end

  def active
    @active_bookings = current_owner.inn.bookings.where(status: :active)
  end

  def cancel
    if current_user
      @booking.canceled! if @booking.confirmed? && Date.today.before?(@booking.cancel_date)
      return redirect_to booking_path(@booking), alert: "Não foi possível cancelar a reserva" unless @booking.canceled?
      redirect_to booking_path(@booking), notice: "Reserva cancelada"

    elsif current_owner
      @booking.canceled! if @booking.confirmed? && Date.today >= @booking.start_date + 2.days
      return redirect_to booking_path(@booking), alert: "Não foi possível cancelar a reserva" unless @booking.canceled?
      redirect_to booking_path(@booking), notice: "Reserva cancelada"

    else
      redirect_to booking_path(@booking), alert: "Não foi possível cancelar a reserva"
    end
  end

  def check_in
    if @booking.start_date <= Date.today

      @booking.guests.build(params[:guests].values)
      @booking.check_in = Time.current
      @booking.status = :active

      if @booking.save
        redirect_to @booking, notice: "Check-in realizado com sucesso"
      else
        redirect_to @booking, alert: "ERRO: Número de hóspedes maior que o informado na reserva"
      end
    else
      redirect_to @booking, alert: "Não foi possível realizar o check-in"
    end
  end

  def check_out
    if @booking.active?
      @booking.update(
        check_out: Time.current,
        status: :closed,
        pay_method: params[:pay_method],
        bill: @booking.calculate_bill
      )
      redirect_to @booking, notice: "Check-out realizado com sucesso"
    else
      redirect_to @booking, alert: "Não foi possível realizar o check-out"
    end
  end

  private

  def authenticate_user_or_owner
    unless user_signed_in? || owner_signed_in?
      redirect_to login_path, notice: "Faça log-in para continuar"
    end
  end

  def authorize_access(booking)
    if (current_owner&. != booking.room.inn.owner) || (current_user&. != booking.user)
      return redirect_to root_path, alert: "Não foi possível completar a requisição"
    end
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_inn
    @inn = @room.inn
  end

  def pre_booking_params
    params.permit(:start_date, :end_date, :number_of_guests, :room_id)
  end

  def booking_params
    params.require(:booking)
          .permit(:start_date, :end_date, :number_of_guests, :room_id)
  end

  def session_params
    { start_date: Date.parse(session.dig("pre_booking", "start_date")),
      end_date: Date.parse(session.dig("pre_booking", "end_date")),
      number_of_guests: session.dig("pre_booking", "number_of_guests").to_i,
      room_id: session.dig("pre_booking", "room_id").to_i }
  end
end

app/views/bookings/_booking.html.erb
<div>
  <dl>
    <dt><%= Booking.model_name.human(count: 1) %>:</dt>
    <dd><%= link_to booking.code, booking_path(booking) %></dd>

    <dt><%= Room.model_name.human(count: 1) %>:</dt>
    <dd><%= booking.room.name %></dd>

    <dt><%= Booking.human_attribute_name(:start_date) %>:</dt>
    <dd><%= l(booking.start_date) %></dd>

    <dt><%= Booking.human_attribute_name(:end_date) %>:</dt>
    <dd><%= l(booking.end_date) %></dd>

    <dt><%= Booking.human_attribute_name(:number_of_guests) %>:</dt>
    <dd><%= booking.number_of_guests %></dd>

    <dt><%= Booking.human_attribute_name(:status) %>:</dt>
    <dd><%= t(booking.status) %></dd>
  </dl>
</div>

app/views/bookings/_booking_card.html.erb
<div class="card">
    <div class="card-header">
        <%= Booking.model_name.human %>:
    </div>
    <div class="card-body">
        <h5><%= link_to booking.code, booking_path(booking) %></h5>
        <dl class="description-list">
            <dt><%= Room.model_name.human %>:</dt>
            <dd><%= booking.room.name %></dd>
            <dt><%= Booking.human_attribute_name(:start_date) %>:</dt>
            <dd><%= I18n.l(booking.start_date) %></dd>
            <dt><%= Booking.human_attribute_name(:end_date) %>:</dt>
            <dd><%= I18n.l(booking.end_date) %></dd>
            <dt><%= Booking.human_attribute_name(:number_of_guests) %>:</dt>
            <dd><%= booking.number_of_guests %></dd>
            <dt><%= Booking.human_attribute_name(:status) %>:</dt>
            <dd><%= t(booking.status) %></dd>
        </dl>
    </div>
</div>

app/views/bookings/_booking_form.html.erb
<%= form_with(url: confirmation_room_bookings_path, method: :get) do |f| %>
  <div class="mb-3">
    <%= f.label :start_date, Booking.human_attribute_name(:start_date), class: "form-label" %>
    <%= f.date_field :start_date, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :end_date, Booking.human_attribute_name(:end_date), class: "form-label" %>
    <%= f.date_field :end_date, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :number_of_guests, Booking.human_attribute_name(:number_of_guests), class: "form-label" %>
    <%= f.number_field :number_of_guests, class: "form-control" %>
  </div>
  <div class="mb-3 text-center">
    <%= f.submit t("advance_button"), class: "btn btn-lg btn-dark" %>
  </div>
<% end %>

app/views/bookings/_my_bookings_card.html.erb
<div class="card">
    <div class="card-header">
    Reserva
    </div>
    <div class="card-body">
        <h5 class="card-title"><%= link_to booking.code, booking %></h5>
        <dl class="list-group list-group-flush">
            <dt><%= Inn.model_name.human count: 1 %>:</dt>
            <dd class="list-group-item"><%= booking.room.inn.name %></dd>
            <dt><%= Room.model_name.human count: 1 %>:</dt>
            <dd class="list-group-item"><%= booking.room.name %></dd>
            <dt><%= t("booking_period") %>:</dt>
            <dd class="list-group-item"><%= I18n.l(booking.start_date) %> - <%= I18n.l(booking.end_date) %></dd>
        </dl>
    </div>
</div>

app/views/bookings/_owner_options.html.erb
<section class="width-70">
  <% if @booking.start_date > Date.today %>

    <p><%= t("check_in_available_from") %> <%= l(@booking.start_date) %></p>

  <% elsif @booking.confirmed? %>

    <div id="guests-registration" class="width-70">
      <h3>Registro de hóspedes</h3>
      <%= form_with(url: check_in_room_booking_path(@room)) do |f| %>
        <% @booking.number_of_guests.times do |i| %>
          <div class="guest-info container">
            <%= f.fields_for "guests[guest_#{i}]" do |g| %>
              <div class="row">
                  <div class="col">
                    <%= g.text_field :name, placeholder: "Nome completo: ", class: "form-control" %>
                  </div>
                  <div class="col">
                    <%= g.text_field :document, placeholder: "RG ou CPF", class: "form-control" %>
                  </div>
              </div>
              <%= g.hidden_field :booking_id, value: @booking.id %>
              <br>
            <% end %>
          </div>
        <% end %>
        <br>
        <div>
          <%= f.submit t("check_in_button"), data: { turbo_confirm: t("check_in_confirm") }, class: "btn btn-lg btn-dark" %>
        </div>
      <% end %>
    </div>

  <% elsif @booking.active? %>

  <%= form_with url: check_out_room_booking_path(@room) do |f| %>
    <div class="row g-3 align-items-center d-flex justify-content-center">
      <div class="col-auto" style="font-size: 20px; font-weight: 100;">
        <%= f.label :pay_method, "Método de pagamento", class: "col-form-label" %>
      </div>
      <div class="col-auto">
        <%= f.text_field :pay_method, class: "form-control" %>
      </div>
      <div class="d-grid gap-2">
        <%= f.submit t("check_out_button"), data: { turbo_confirm: t("check_out_confirm") }, class: "btn btn-lg btn-dark" %>
      </div>
    </div>
  <% end %>

  <% end %>

  <% if Date.today >= @booking.start_date + 2.days && @booking.confirmed? %>
    <%= button_to t("cancel_booking_button"), cancel_room_booking_path(@room), data: { turbo_confirm: t("cancel_booking_confirm") } %>
  <% end %>
</section>

app/views/bookings/_user_canceling.html.erb
<% if @booking.confirmed? && @booking.cancel_date > Date.today %>
  <div>
    <p><%= t("cancel_booking_until") %> <strong><%= l(@booking.cancel_date) %></strong></p>
    <%= button_to t("cancel_booking_button"), cancel_room_booking_path(@room.id), data: { turbo_confirm: t("cancel_booking_confirm") } %>
  </div>
<% elsif @booking.confirmed? && @booking.cancel_date <= Date.today %>
  <div>
    <p><%= t("booking_cant_be_canceled") %></p>
  </div>
<% end %>

app/views/bookings/_user_options.html.erb
<div>
  <% if @booking.confirmed? && @booking.cancel_date > Date.today %>
    <div>
      <p><%= t("cancel_booking_until") %> <strong><%= l(@booking.cancel_date) %></strong></p>
      <%= button_to t("cancel_booking_button"), cancel_room_booking_path(@room.id), data: { turbo_confirm: t("cancel_booking_confirm") }, class: "btn btl-lg btn-dark" %>
    </div>
  <% elsif @booking.confirmed? && @booking.cancel_date <= Date.today %>
    <div>
      <p><%= t("booking_cant_be_canceled") %></p>
    </div>
  <% elsif @booking.closed? && @review.nil? %>
    <div>
      <%= link_to "Avaliar", new_booking_review_path(@booking), class: "btn btn-lg btn-outline-success" %>
    </div>
  <% end %>
</div>

<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/bookings/active.html.erb
<section id="active-bookings" class="width-70">
  <div class="text-center">
    <h1><%= t("active_bookings") %></h1>
  </div>

  <% if @active_bookings.empty? %>
    <div class="text-center">
      <p><%= t("no_active_booking") %></p>
    </div>
  <% end %>

  <section id="active-bookings-list">
    <div class="row d-flex justify-content-center">
      <% @active_bookings.each do |booking| %>
        <div class="col-md-4">
          <%= render partial: "booking_card", locals: { booking: booking } %>
        </div>
      <% end %>
    </div>
  </section>

</section>
  <%= link_to t("back_link"), root_path %>

app/views/bookings/confirmation.html.erb
<div class="list-formatting">
  <h1 class="text-center"><%= t("booking_details") %></h1>

  <dl class="list-group list-group-flush">
    <dt><%= Room.model_name.human(count: 1) %>:</dt>
    <dd class="list-group-item"> <%= @room.name %></dd>

    <dt><%= Booking.human_attribute_name(:start_date) %>:</dt>
    <dd class="list-group-item"><%= I18n.l(@pre_booking.start_date) %> a partir das <%= @inn.check_in_time.strftime("%H:%M") %> horas</dd>

    <dt><%= Booking.human_attribute_name(:end_date) %>:</dt>
    <dd class="list-group-item"><%= I18n.l(@pre_booking.end_date) %> até as <%= @inn.check_out_time.strftime("%H:%M") %> horas</dd>

    <dt><%= Booking.human_attribute_name(:number_of_guests) %>:</dt>
    <dd class="list-group-item"><%= @pre_booking.number_of_guests %></dd>

    <dt><%= Booking.human_attribute_name(:bill) %>:</dt>
    <dd class="list-group-item"><%= number_to_currency @pre_booking.calculate_bill, unit: "R$", separator: ",", delimiter: "." %></dd>

    <dt><%= t("payment_methods") %>:</dt>
    <dd class="list-group-item"><%= @inn.pay_methods %></dd>
  </dl>

  <br>

  <div class="text-center">
    <div class="d-grid gap-2">
      <%= button_to t("confirm_booking_button"), room_bookings_path, class: "btn btn-lg btn-dark" %>
    </div>

    <br>

    <%= link_to t("back_link"), new_room_booking_path(params[:room_id]), class: "btn btn-lg btn-outline-dark" %>
  </div>
</div>

app/views/bookings/index.html.erb
<section>
  <br>

  <div class="text-center">
    <h1><%= Booking.model_name.human count: 2 %> - <%= @inn.name %></h1>
  </div>

  <br>

  <% if @bookings.empty? %>
    <div class="text-center">
      <p><%= t("no_bookings_found") %></p>
    </div>
  <% end %>
  
  <div id="bookings-list" class="row d-flex justify-content-center">
    <% @bookings.each do |booking| %>
      <div class="col-md-4 mb-3">
        <%= render partial: "booking_card", locals: { booking: booking } %>
      </div>
    <% end %>
  </div>
</section>

app/views/bookings/my_bookings.html.erb
<div class="text-center">
  <h1><%= Booking.model_name.human count: 2 %></h1>
</div>

<% if @bookings.empty? %>
  <p><%= t("no_bookings_found_for_user") %></p>
<% end %>

<div id="bookings-list" class="container">
  <div class="row d-flex justify-content-center">
    <% @bookings.each do |booking| %>
      <div class="col-md-4 mb-3">
        <%= render partial: "my_bookings_card", locals: { booking: booking } %>
      </div>
    <% end %>
  </div>
</div>


<div id="closed-bookings" class="container">
  <div class="row d-flex justify-content-center">
    <h2><%= t("closed_bookings") %></h2>
      <% @closed_bookings.each do |closed_booking| %>
        <div class="col-md-4 mb-3">
          <%= render partial: "my_bookings_card", locals: { booking: closed_booking } %>
        </div>
      <% end %>
  </div>
</div>

<br>

<div class="text-center">
  <%= link_to t("back_to_beginning_link"), root_path, class: "btn btn-lg btn-outline-dark" %>
</div>

app/views/bookings/new.html.erb
<section class="form">
    <%= render partial: "shared/form_errors", locals: { model: @pre_booking } %>

    <h1 class="text-center"><%= t "booking_details" %></h1>

    <div id="booking-inn-room-names" class="text-center">
        <h4><%= Inn.model_name.human(count: 1) %>: <%= @inn.name %></h4>
        <h4><%= Room.model_name.human(count: 1) %>: <%= @room.name %></h4>
    </div>

    <%= render partial:("booking_form") %>

    <%= link_to t("back_link"), @room %>
</section>

app/views/bookings/show.html.erb
<h1 class="text-center"><%= I18n.t("booking_details") %></h1>

<section class="list-formatting">
  <div class="text-center">
    <h2><%= @inn.name %></h2>
    <h3><%= Room.model_name.human(count: 1) %>: <%= @room.name %></h3>
  </div>

  <dl class="list-group list-group-flush">
    <dt><%= Booking.human_attribute_name(:check_in) %>:</dt>
    <dd class="list-group-item"><%= l(@booking.start_date) %> a partir das <%= @inn.check_in_time.strftime("%H:%M") %> horas</dd>

    <dt><%= Booking.human_attribute_name(:check_out) %>:</dt>
    <dd class="list-group-item"><%= l(@booking.end_date) %> até as <%= @inn.check_out_time.strftime("%H:%M") %> horas</dd>

    <dt><%= Booking.human_attribute_name(:number_of_guests) %>:</dt>
    <dd class="list-group-item"><%= @booking.number_of_guests %></dd>

    <% if @booking.guests.present? %>
      <dt>Hóspedes</dt>
      <dd>
        <% @booking.guests.each do |guest| %>
          <dt>Nome:</dt>
          <dd><%= guest.name %></dd>
          <dt>Documento:</dt>
          <dd><%= guest.document %></dd>
        <% end %>
      </dd>
      <dd></dd>
      <dt class="list-group-item"></dt>
    <% end %>

    <dt><%= Booking.human_attribute_name(:bill) %>:</dt>
    <dd class="list-group-item"><%= number_to_currency @booking.calculate_bill, unit: "R$", delimiter: ".", separator: "," %></dd>

    <dt><%= Booking.human_attribute_name(:code) %>:</dt>
    <dd class="list-group-item"><%= @booking.code %></dd>

    <dt><%= Booking.human_attribute_name(:status) %>:</dt>
    <dd class="list-group-item"><%= t(@booking.status) %></dd>
  </dl>
</section>

<% if @review.present? %>
  <section id="review" class="width-70 d-flex justify-content-center">
    <div class="card" style="width: 40vw;">
      <div class="card-header text-center">
        <h5>Avaliação</h5>
      </div>
      <div class="card-body">
        <dl class="description-list">
          <div class="row">
            <div class="col">
              <dt>Nota:</dt>
              <dd><%= @review.score %></dd>
            </div>
            <div class="col">
              <dt>Mensagem:</dt>
              <dd><%= @review.message %></dd>
            </div>
          </div>
        </dl>
        <hr>
        <section id="review-answer" class="text-center">
          <%= render partial: "reviews/review_answer" %>
        </section> 
      </div>
    </div>
  </section>

<% end %>

<section id="booking-options" class="text-center">
  <% if current_user %>
    <%= render partial: "user_options" %>
  <% elsif current_owner %>
    <%= render partial: "owner_options" %>
  <% end %>
</section>

<br>

<div class="text-center">
  <% if owner_signed_in? %>
    <%= link_to t("back_link"), bookings_path, class: "btn btn-lg btn-outline-dark" %>
  <% else %>
    <%= link_to t("back_link"), my_bookings_path, class: "btn btn-lg btn-outline-dark" %>
  <% end %>
</div>