config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: "owners", controllers: {
    sesions: "owners/sessions",
    registrations: "owners/registrations",
    passwords: "owners/passwords",
    confirmations: "owners/confirmations",
    unlocks: "owner/unlocks"
  }

  devise_for :users, path: "users", controllers: {
    sesions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  root "home#index"
  get "logins", to: "home#logins"
  get "minha_pousada", to: "inns#my_inn", as: "my_inn"
  get "minhas_reservas", to: "bookings#my_bookings", as: "my_bookings"

  resources :addresses, only: [:new, :create]

  resources :inns, only: [:new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    get "search", on: :collection
    get "city_search", on: :collection
    get "advanced_search", on: :collection
    delete "remove_photo", on: :member

    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:index, :new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    delete "remove_photo", on: :member

    resources :seasonal_prices, only: [:new, :create]

    resources :bookings, only: [:new, :create] do
      get "confirmation", on: :collection
      post "cancel", on: :member
      post "check_in", on: :member
      post "check_out", on: :member
    end
  end

  resources :bookings, only: [:index, :show] do
    get "active", on: :collection

    resources :reviews, only: [:new, :create] do
      post "answer", on: :member
    end
  end

  resources :seasonal_prices, only: [:show, :edit, :update, :destroy]

  resources :reviews, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get "cities", on: :collection
      end

      resources :bookings, only: [] do
        get "pre-booking", on: :collection
      end
    end
  end
end

app/models/inn.rb
class Inn < ApplicationRecord
  has_one :address
  belongs_to :owner
  has_many :rooms
  has_many :bookings, through: :rooms
  has_many :reviews, through: :bookings
  has_many_attached :photos

  accepts_nested_attributes_for :address

  validates :name,
            :corporate_name,
            :registration_number,
            :phone,
            :email,
            :pay_methods,
            presence: true
  validates :photos, content_type: {
    in: ["image/jpg", "image/jpeg", "image/png"],
    message: "somente nos formatos JPG, JPEG ou PNG"
  }
  validates :photos, size: { less_than: 5.megabytes, message: "não pode ser maior que 5 mb" }
  validate :validates_registration_number
  validate -> { max_number_of_photos(5) }

  def self.search_inns(query)
    Inn.joins(:address)
       .where(active: true)
       .where("name LIKE :query OR city LIKE :query OR neighborhood LIKE :query",
               query: "%#{query}%")
       .order(:name)
  end

  def self.advanced_search(params)
    @inns = Inn.joins(:address, :rooms).where(active: true)
    @inns = @inns.where("inns.name LIKE ?", "%#{params[:name]}%") if params[:name].present?
    @inns = @inns.where("addresses.city LIKE ?", "%#{params[:city]}%") if params[:city].present?
    @inns = @inns.where(inns: { pet_friendly: true }) if params[:pet_friendly] == "1"

    room_params = self.room_params(params)

    @inns = @inns.where(rooms: room_params) if room_params.present?
    @inns.uniq
  end

  def self.all_cities
    Inn.joins(:address).where(active: true).pluck(:city).uniq.sort
  end

  def self.from_city(city)
    Inn.joins(:address)
       .where(active: true)
       .where("city_ascii LIKE ?", "%#{I18n.transliterate(city)}%")
  end

  def average_score
    bookings.joins(:review).average("score")&.round(1) || ""
  end

  def formatted_check_in_time
    check_in_time.strftime("%H:%M")
  end

  def formatted_check_out_time
    check_out_time.strftime("%H:%M")
  end

  private

  def validates_registration_number
    cnpj = BrDocuments::CnpjCpf::Cnpj.new(registration_number)
    errors.add(:registration_number, " inválido") unless cnpj.valid?
  end

  def self.room_params(params)
    room_params = {}
    room_params[:accessibility] = true if params[:accessibility] == "1"
    room_params[:wifi] = true if params[:wifi] == "1"
    room_params[:bathroom] = true if params[:bathroom] == "1"
    room_params[:air_conditioner] = true if params[:air_conditioner] == "1"
    room_params[:wardrobe] = true if params[:wardrobe] == "1"
    room_params[:tv] = true if params[:tv] == "1"
    room_params[:porch] = true if params[:porch] == "1"
    room_params[:safe] = true if params[:safe] == "1"
    room_params
  end
end

app/controllers/api/v1/inns_controller.rb
class Api::V1::InnsController < Api::V1::ApiController
  def index
    inns = Inn.joins(:address)
              .where(active: true)
              .where("name LIKE ?", "%#{params[:name]}%")

    render status: 200, json: inns.as_json(
      only: inn_permitted_attributes,
      methods: json_method_calls,
      include: { address: { only: address_permitted_attributes } }
    )
  end

  def show
    inn = Inn.find_by(id: params[:id], active: true)

    return inn_not_found if inn.nil?

    render status: 200, json: inn.as_json(
      only: inn_permitted_attributes,
      methods: json_method_calls,
      include: { address: { only: address_permitted_attributes } }
    )
  end

  def cities
    if params[:city].present?
      inns = Inn.from_city(params[:city])

      render status: 200, json: inns.as_json(
        only: inn_permitted_attributes,
        include: { address: { only: address_permitted_attributes } }
      )
    else
      render status: 200, json: {"cidades": Inn.all_cities}
    end
  end

  private

  def inn_permitted_attributes
    [
      :id,
      :name,
      :phone,
      :email,
      :description,
      :pay_methods,
      :pet_friendly,
      :user_policies
    ]
  end

  def address_permitted_attributes
    [
      :street,
      :number,
      :neighborhood,
      :city, :state,
      :postal_code
    ]
  end

  def json_method_calls
    [
      :formatted_check_in_time,
      :formatted_check_out_time,
      :average_score
    ]
  end
end

app/controllers/inns_controller.rb
class InnsController < ApplicationController
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :change_status, :remove_photo]
  before_action :redirect_to_new_if_no_inn, only: [:show, :my_inn]
  before_action :set_inn, only: [:show, :edit, :update, :change_status, :remove_photo]


  def new
    if current_owner.inn
      redirect_to inn_path(current_owner.inn), notice: "Você já tem uma pousada cadastrada"
    else
      @inn = Inn.new
      @inn.build_address
    end
  end

  def create
    @inn = current_owner.build_inn(inn_params)
    @inn.check_in_time = get_time(:checkin_hour, :checkin_minute)
    @inn.check_out_time = get_time(:checkout_hour, :checkout_minute)

    if @inn.save
      redirect_to my_inn_path, notice: "Pousada criada com sucesso"
    else
      @address = @inn.address
      flash.now[:alert] = "Erro ao cadastrar Pousada"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @rooms = @inn.rooms.where(active: true)
    @average_score = @inn.average_score
    @recent_reviews = @inn.reviews.order(created_at: :desc).limit(3)
  end

  def edit
    @address = @inn.address
  end

  def update
    @inn.check_in_time = get_time(:checkin_hour, :checkin_minute)
    @inn.check_out_time = get_time(:checkout_hour, :checkout_minute)
    @inn.address.update(inn_params[:address_attributes])

    if @inn.update(inn_params.except(:address_attributes))
      redirect_to my_inn_path, notice: "Pousada atualizada com sucesso"
    else
      @address = @inn.address
      flash.now[:alert] = "Erro ao atualizar Pousada"
      render :edit, status: :unprocessable_entity
    end
  end

  def my_inn
    @inn = current_owner.inn
    @rooms = @inn.rooms
  end

  def change_status
    @inn.active = !@inn.active

    if @inn.save
      redirect_to my_inn_path, notice: "Pousada editada com sucesso"
    else
      redirect_to my_inn_path, alert: "Erro ao editar Pousada"
    end
  end

  def search
    @inns = Inn.search_inns(params[:query]) if params[:query]
    @inns = Inn.advanced_search(advanced_params) if params[:advanced]
  end

  def city_search
    @found_inns = Inn.joins(:address)
                     .where(active: true)
                     .where(address: { city: params[:city] })
                     .order(:name)
  end

  def remove_photo
    return redirect_to root_path unless current_owner == @inn.owner

    @inn.photos.find(params[:photo_id]).purge
    redirect_to my_inn_path
  end

  private

  def inn_params
    params.require(:inn).permit(
      :name,
      :corporate_name,
      :registration_number,
      :phone,
      :email,
      :description,
      :pay_methods,
      :pet_friendly,
      :user_policies,
      :active,
      address_attributes: [
        :street,
        :number,
        :neighborhood,
        :city,
        :state,
        :postal_code
      ],
      date: [
        :checkin_hour,
        :chekin_minute,
        :checkout_hour,
        :checkout_minute
      ],
      photos: []
    )
  end

  def advanced_params
    params.permit(
      :name,
      :city,
      :pet_friendly,
      :accessibility,
      :wifi,
      :bathroom,
      :air_conditioner,
      :wardrobe,
      :tv,
      :porch,
      :safe
    )

  end

  def set_inn
    @inn = Inn.find(params[:id])
  end

  def get_time(hour, minute)
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      params[:date][hour],
      params[:date][minute],
      0,
      "UTC"
    )
  end
end

app/views/inns/_inn.html.erb
<div class="inn-card">
    <h3><%= link_to inn.name, inn %></h3>
    <% if inn.photos.attached? %>
        <div class="photo-container">
            <%= link_to image_tag(inn.photos.first.variant(resize_to_limit: [300, 300]).processed), inn %>
        </div>
    <% end %>
    <p><%= inn.address.city %> - <%= inn.address.state %></p>
</div>

app/views/inns/_inn_card.html.erb
<div class="card h-100 mb-3">
	<% if inn.photos.attached? %>
		<%= image_tag(inn.photos.first, class: "card-img-top") %>
	<% else %>
		<img src="https://archive.org/download/placeholder-image/placeholder-image.jpg" alt="no image" class="card-img-top" width="100px">
	<% end %>
	<div class="card-body">
		<h4 class="card-title"><%= link_to inn.name, inn_path(inn) %></h4>
		<p class="card-text"><%= inn.description %></p>
		<address class="card-text">
			<%= inn.address.city %> - <%= inn.address.state %>
		</address>
	</div>
</div>

app/views/inns/_inn_display.html.erb
  <dl>
    <dt>Nome público:</dt>
    <dd><%= @inn.name %></dd>
    <dt>Razão social:</dt>
    <dd><%= @inn.corporate_name %></dd>
    <dt>CNPJ:</dt>
    <dd><%= @inn.registration_number %></dd>
    <dt>Telefone:</dt>
    <dd><%= @inn.phone %></dd>
    <dt>E-mail:</dt>
    <dd><%= @inn.email %></dd>
    <dt>Descrição:</dt>
    <dd><%= @inn.description %></dd>
    <dt>Métodos de pagamento:</dt>
    <dd><%= @inn.pay_methods %></dd>
    <dt>Aceita pets:</dt>
    <dd><%= @inn.pet_friendly ? "sim" : "não" %></dd>
    <dt>Políticas de uso:</dt>
    <dd><%= @inn.user_policies %></dd>
    <dt>Check-in:</dt>
    <dd>a partir das <%= @inn.check_in_time.strftime("%k:%M") %></dd>
    <dt>Check-out:</dt>
    <dd>até as <%= @inn.check_out_time.strftime("%k:%M") %></dd>
    <dt>Endereço:</dt>
    <dd><%= @inn.get_street_values %></dd>
    <dd><%= @inn.get_location_values %></dd>
    <dt>CEP:</dt>
    <dd><%= @inn.address.postal_code %></dd>
    <dt>Status na plataforma:</dt>
    <dd><%= @inn.active ? "Ativa" : "Desativada" %></dd>
  </dl>

app/views/inns/advanced_search.html.erb
<h1 style="text-align: center; margin-top: 20px;"><%= t("advanced_search") %></h1>

  <div class="mb-3 form" id="advanced-search-form">
    <%= form_with(url: search_inns_path, method: :get) do |f| %>
      <div>
        <%= f.label :name, "Nome", class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div>
        <%= f.label :city, "Cidade", class: "form-label" %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="switches">
        <div class="form-check form-switch">
          <%= f.label :pet_friendly, "Aceita pets", class: "form-check-label" %>
          <%= f.check_box :pet_friendly, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :accessibility, "Acessível para PCD", class: "form-check-label" %>
          <%= f.check_box :accessibility, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :wifi, "Wi-fi", class: "form-check-label" %>
          <%= f.check_box :wifi, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :bathroom, "Banheiro privativo", class: "form-check-label" %>
          <%= f.check_box :bathroom, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :air_conditioner, "Ar-condicionado", class: "form-check-label" %>
          <%= f.check_box :air_conditioner, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :wardrobe, "Guarda-roupas", class: "form-check-label" %>
          <%= f.check_box :wardrobe, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :tv, "TV", class: "form-check-label" %>
          <%= f.check_box :tv, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :porch, "Varanda", class: "form-check-label" %>
          <%= f.check_box :porch, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :safe, "Cofre", class: "form-check-label" %>
          <%= f.check_box :safe, class: "form-check-input" %>
        </div>
      </div>
      <%= f.hidden_field :advanced, { value: true } %>
      <div class="text-center">
        <%= f.submit t("search_button"), class: "btn btn-lg btn-dark" %>
      </div>
    <% end %>
  </div>

app/views/inns/city_search.html.erb
<section id="city-search-results">
  <h1><%= Inn.model_name.human(count: 2) %> em: <%= params[:city] %></h1>

  <div class="container">
      <div class="row justify-content-center">
        <% @found_inns.each do |inn| %>
          <div class="col-md-4">
            <%= render partial: "inn_card", locals: { inn: inn } %>
          </div>
        <% end %>
      </div>
    <div class="mt-5">
      <%= link_to t("back_link"), root_path, class: "btn btn-lg btn-dark" %>
    </div>
  </div>
</section>

app/views/inns/edit.html.erb
<%= render partial: "shared/form_errors", locals: { model: @inn }%>

<section class="form">
    <h1>Editar <%= Inn.model_name.human(count: 1) %></h1>

    <%= render partial: "inn_form" %>

    <br>

    <div class="text-center d-grid gap-2 col-6 mx-auto">
        <% if @inn.active? %>
            <%= button_to "Desativar Pousada", change_status_inn_path, { method: "patch", class: "btn btn-lg btn-danger" } %>
        <% else %>
            <%= button_to "Ativar Pousada", change_status_inn_path, { method: "patch", class: "btn btn-lg btn-success" } %>
        <% end %>
    </div>

    <br>

    <div class="text-center">
        <%= link_to t("back_link"), my_inn_path, class: "btn btn-outline-dark" %>
    </div>
</section>

app/views/inns/my_inn.html.erb
<section class="width-70">
  <dl class="list-group list-group-flush">
      <dt><%= Inn.human_attribute_name(:name) %>:</dt>
      <dd class="list-group-item"><%= @inn.name %></dd>

      <dt><%= Inn.human_attribute_name(:corporate_name) %>:</dt>
      <dd class="list-group-item"><%= @inn.corporate_name %></dd>

      <dt><%= Inn.human_attribute_name(:registration_number) %>:</dt>
      <dd class="list-group-item"><%= @inn.registration_number %></dd>

      <dt><%= Inn.human_attribute_name(:phone) %>:</dt>
      <dd class="list-group-item"><%= @inn.phone %></dd>

      <dt><%= Inn.human_attribute_name(:email) %>:</dt>
      <dd class="list-group-item"><%= @inn.email %></dd>

      <dt><%= Inn.human_attribute_name(:description) %>:</dt>
      <dd class="list-group-item"><%= @inn.description %></dd>

      <dt><%= Inn.human_attribute_name(:pay_methods) %>:</dt>
      <dd class="list-group-item"><%= @inn.pay_methods %></dd>

      <dt><%= Inn.human_attribute_name(:pet_friendly) %>:</dt>
      <dd class="list-group-item"><%= @inn.pet_friendly ? "sim" : "não" %></dd>

      <dt><%= Inn.human_attribute_name(:user_policies) %>:</dt>
      <dd class="list-group-item"><%= @inn.user_policies %></dd>

      <dt><%= Inn.human_attribute_name(:check_in_time) %>:</dt>
      <dd class="list-group-item">a partir das <%= @inn.check_in_time.strftime("%k:%M") %></dd>

      <dt><%= Inn.human_attribute_name(:check_out_time) %>:</dt>
      <dd class="list-group-item">até as <%= @inn.check_out_time.strftime("%k:%M") %></dd>

      <dt><%= Address.model_name.human %>:</dt>
      <dd><%= @inn.address.street_values %></dd>
      <dd class="list-group-item"><%= @inn.address.location_values %></dd>

      <dt><%= Address.human_attribute_name(:postal_code) %>:</dt>
      <dd class="list-group-item"><%= @inn.address.postal_code %></dd>

      <dt><%= t("inn_status_text") %>:</dt>
      <dd class="list-group-item"><%= @inn.active ? "Ativa" : "Desativada" %></dd>

      <dt>Fotos:</dt>
      <dd class="list-group-item">
        <div class="row">
          <% @inn.photos.each do |photo| %>
            <div class="col-md-4">
              <div class="card text-center">
                <%= image_tag(photo.variant(resize_to_limit: [150, 150]).processed, class: "card-img-top")  %>
                <div class="card-body">
                  <%= button_to "Remover", remove_photo_inn_path(@inn), method: :delete, params: { photo_id: photo.id }, data: { turbo_method: :delete, turbo_confirm: "Remover foto?" }, class: "btn btn-outline-danger" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </dd>
    </dl>

  <div class="text-center">
    <%= link_to "Editar Pousada", edit_inn_path(@inn), class: "btn btn-lg btn-dark" %>
  </div>

  <br>
  <hr>

  <div id="rooms" class="width-70">
    <h2><%= Room.model_name.human(count: 2) %></h2>
    <%= render partial: "rooms/rooms_list" %>
  </div>
</section>

app/views/inns/new.html.erb
<%= render partial: "shared/form_errors", locals: { model: @inn } %>

<section class="form">
  <h1><%= t("inn_registration") %></h1>

  <%= render partial: "inn_form" %>
</section>

app/views/inns/search.html.erb
<div class="container">
  <div class="mt-5 mb-5 text-center">
    <h1><%= t("search_for") %>: <%= params[:query] %></h1>
    <p><%= t("results") %>: <%= @inns.count %></p>
  </div>


  <% if @inns.empty? %>
    <div class="text-center">
      <p><%= t("no_inn_found") %></p>
    </div>
  <% else %>
    <div class="d-flex justify-content-center">
      <div class="row">
        <% @inns.each do |inn| %>
          <div class="col mb-3">
            <%= render partial: "inn_card", locals: { inn: inn } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/inns/show.html.erb
<section class="details">
  <div class="mb-3 mt-5">
    <h1><%= @inn.name %></h1>
  </div>
  <% if @inn.photos.attached? %>
    <div id="inn-photo-carousel" class="carousel slide">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#inn-photo-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#inn-photo-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#inn-photo-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <% @inn.photos.each do |photo| %>
          <div class="carousel-item active">
            <%= image_tag(photo, class: "d-block w-100") %>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#inn-photo-carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#inn-photo-carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Próxima</span>
      </button>
    </div>
  <% end %>

  <div>
    <dl class="description-list list-group list-group-flush">
      <dt><%= Review.model_name.human(count: 1) %>:</dt>
      <% if @average_score.blank? %>
        <dd class="list-group-item"><%= t("no_reviews") %></dd>
      <% else %>
        <dd class="list-group-item"><%= @average_score %></dd>
      <% end %>
      <dt><%= Inn.human_attribute_name(:name) %>:</dt>
      <dd class="list-group-item"><%= @inn.name %></dd>

      <dt><%= Inn.human_attribute_name(:phone) %>:</dt>
      <dd class="list-group-item"><%= @inn.phone %></dd>

      <dt><%= Inn.human_attribute_name(:email) %>:</dt>
      <dd class="list-group-item"><%= @inn.email %></dd>

      <dt><%= Inn.human_attribute_name(:description) %>:</dt>
      <dd class="list-group-item"><%= @inn.description %></dd>

      <dt><%= Inn.human_attribute_name(:pay_methods) %>:</dt>
      <dd class="list-group-item"><%= @inn.pay_methods %></dd>

      <dt><%= Inn.human_attribute_name(:pet_friendly) %>:</dt>
      <dd class="list-group-item"><%= @inn.pet_friendly ? "sim" : "não" %></dd>

      <dt><%= Inn.human_attribute_name(:user_policies) %>:</dt>
      <dd class="list-group-item"><%= @inn.user_policies %></dd>

      <dt><%= Inn.human_attribute_name(:check_in_time) %>:</dt>
      <dd class="list-group-item">a partir das <%= @inn.check_in_time.strftime("%k:%M") %></dd>

      <dt><%= Inn.human_attribute_name(:check_out_time) %>:</dt>
      <dd class="list-group-item">até as <%= @inn.check_out_time.strftime("%k:%M") %></dd>

      <dt><%= Address.model_name.human %>:</dt>
      <dd class="list-group-item">
        <address>
          <%= @inn.address.street_values %> <br>
          <%= @inn.address.location_values %>
        </address>
        </dd>

      <dt><%= Address.human_attribute_name(:postal_code) %>:</dt>
      <dd class="list-group-item"><%= @inn.address.postal_code %></dd>
    </dl>
  </div>

  <h2><%= t("available_rooms") %>:</h2>

  <div id="rooms-list" class="row">
    <% @rooms.each do |room| %>
      <div class="col-md-4">
        <div class="card">
          <% if room.photos.attached? %>
            <%= image_tag(room.photos.first, class: "card-img-top") %>
          <% else %>
            <img src="https://archive.org/download/placeholder-image/placeholder-image.jpg" alt="no image" class="card-img-top" width="100px">
          <% end %>
          <div class="card-body">
            <h4 class="card-title"><%= link_to room.name, room_path(room) %></h4>
            <p class="card-text"><%= room.description %></p>
            <p class="card-text">Valor da diária: <%= number_to_currency room.price, unit: "R$", separator: ",", delimiter: "." %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <br>

  <section id="recent-reviews">
    <h3><%= t("recent_reviews") %></h3>
    <% @recent_reviews.each do |review| %>
      <div class="row d-flex justify-content-center">
        <div class="col">
          <div class="card w-50">
            <dl>
                <div class="card-header">
                  <div class="row">
                    <div class="col">
                      <dt><%= User.model_name.human(count: 1) %>:</dt>
                      <dd><%= review.booking.user.name %></dd>
                    </div>
                  <% if current_owner %>
                    <div class="col">
                      <dt><%= Booking.model_name.human(count: 1) %>:</dt>
                      <dd><%= link_to review.booking.code, booking_path(review.booking) %></dd>
                    </div>
                  <% end %>
                  </div>
                </div>
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <dt><%= Review.human_attribute_name(:score) %>:</dt>
                    <dd><%= review.score %></dd>
                  </div>
                  <div class="col">
                    <dt><%= Review.human_attribute_name(:message) %>:</dt>
                    <dd><%= review.message %></dd>
                  </div>
                </div>
                <hr>
                <div class="text-center">
                  <dt><%= t("owner_answer") %>:</dt>
                  <dd><%= review.answer %></dd>
                </div>
              </div>
            </dl>
          </div>
        </div>
      </div>        
    <% end %>
    <div>
      <%= link_to t("back_link"), root_path, class: "btn btn-lg btn-outline-dark" %>
      <%= link_to t("view_all_reviews"), inn_reviews_path(@inn), class: "btn btn-lg btn-outline-success" %>
    </div>
  </section>

  <br>

</section>