config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: "owners", controllers: {
    sesions: "owners/sessions",
    registrations: "owners/registrations",
    passwords: "owners/passwords",
    confirmations: "owners/confirmations",
    unlocks: "owner/unlocks"
  }

  devise_for :users, path: "users", controllers: {
    sesions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  root "home#index"
  get "logins", to: "home#logins"
  get "minha_pousada", to: "inns#my_inn", as: "my_inn"
  get "minhas_reservas", to: "bookings#my_bookings", as: "my_bookings"

  resources :addresses, only: [:new, :create]

  resources :inns, only: [:new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    get "search", on: :collection
    get "city_search", on: :collection
    get "advanced_search", on: :collection
    delete "remove_photo", on: :member

    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:index, :new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    delete "remove_photo", on: :member

    resources :seasonal_prices, only: [:new, :create]

    resources :bookings, only: [:new, :create] do
      get "confirmation", on: :collection
      post "cancel", on: :member
      post "check_in", on: :member
      post "check_out", on: :member
    end
  end

  resources :bookings, only: [:index, :show] do
    get "active", on: :collection

    resources :reviews, only: [:new, :create] do
      post "answer", on: :member
    end
  end

  resources :seasonal_prices, only: [:show, :edit, :update, :destroy]

  resources :reviews, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get "cities", on: :collection
      end

      resources :bookings, only: [] do
        get "pre-booking", on: :collection
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :inn
  has_many :seasonal_prices
  has_many :bookings
  has_many_attached :photos

  validates :name,
            :size,
            :max_guests,
            :price,
            presence: true
  validates :size,
            :max_guests,
            :price,
            numericality: { greater_than: 0 }
  validates :photos, content_type: {
    in: ["image/jpg", "image/jpeg", "image/png"],
    message: "somente nos formatos JPG, JPEG ou PNG"
  }
  validates :photos, size: { less_than: 5.megabytes, message: "não pode ser maior que 5 mb" }
  validate -> { max_number_of_photos(5) }
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::ApiController
  def index
    inn = Inn.find_by(id: params[:inn_id], active: true)

    return inn_not_found if inn.nil?

    rooms = inn.rooms.where(active: true)
    render status: 200, json: rooms.as_json(only: room_permitted_attributes)
  end

  private

  def room_permitted_attributes
    [
      :id,
      :name,
      :description,
      :size,
      :max_guests,
      :price,
      :bathroom,
      :porch,
      :air_conditioner,
      :tv,
      :wardrobe,
      :safe,
      :wifi,
      :accessibility
    ]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :change_status, :remove_photo]
  before_action :authenticate_current_owner, only: [:edit, :update, :change_status, :remove_photo]
  before_action :authenticate_owner!, only: [:index, :new, :create, :edit,
                                             :update, :change_status, :remove_photo]

  def index
    @inn = current_owner.inn
    @rooms = @inn.rooms
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_owner.inn.rooms.build(room_params)
    if @room.save
      redirect_to @room, notice: "Quarto cadastrado com sucesso!"
    else
      flash.now[:alert] = "Erro ao cadastrar quarto!"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @seasonal_prices = SeasonalPrice.where("room_id = ?", @room.id).order(:start)
  end

  def edit; end

  def update
    @room.update(room_params)

    if @room.save
      redirect_to @room, notice: "Quarto atualizado com sucesso!"
    else
      flash.now[:alert] = "Erro ao atualizar quarto!"
      render :edit, status: :unprocessable_entity
    end
  end

  def change_status
    @room.active = !@room.active
    @room.save
    redirect_to @room, notice: "Quarto atualizado com sucesso!"
  end

  def remove_photo
    @room.photos.find_by(id: params[:photo_id]).purge
    redirect_to @room
  end

  private

  def room_params
    params.require(:room).permit(
      :name,
      :description,
      :size,
      :max_guests,
      :price,
      :bathroom,
      :porch,
      :air_conditioner,
      :tv,
      :wardrobe,
      :safe,
      :wifi,
      :accessibility,
      :active,
      photos: []
    )
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def authenticate_current_owner
    return redirect_to logins_path if current_owner.nil?

    if current_owner != @room.inn.owner
      redirect_to root_path, alert: "Você não tem permissão para acessar essa página!"
    end
  end
end

app/views/rooms/_room.html.erb
<section>
  <div class="mt-5 mb-3 text-center">
    <h3>Quarto: <%= link_to room.name, room_path(room) %></h3>
  </div>
  
  <% if owner_signed_in? %>
    <% if room.photos.attached? %>
      <div class="photo-gallery row d-flex justify-content-center">
        <% room.photos.each do |photo| %>
          <div class="col-5">
            <div class="card" style="width: 25vw;">
              <div class="card-header">
                <h6>Foto</h6>
              </div>
              <div class="card-image-top">
                <%= link_to image_tag(photo.variant(resize_to_limit: [250, 250]).processed), photo %>
              </div>
              <div class="card-body">
                <%= button_to "Remover", remove_photo_room_path(room), params: { photo_id: photo.id }, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Remover foto?" }, class: "btn btn-sm btn-danger" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  <% else %>  
    <% if room.photos.attached? %>
      <div id="room-photo-carousel" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#room-photo-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#room-photo-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#room-photo-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <% @room.photos.each do |photo| %>
              <div class="carousel-item active">
                <%= image_tag(photo, class: "d-block w-100") %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#room-photo-carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#room-photo-carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Próxima</span>
          </button>
        </div>
    <% end %>
  <% end %>

  <dl class="description-list list-group list-group-flush">
    <dt>Descrição: </dt>
    <dd class="list-group-item"><%= room.description %></dd>
    <dt>Tamanho:</dt>
    <dd class="list-group-item"><%= room.size %> m²</dd>
    <dt>Número máximo de hóspedes:</dt>
    <dd class="list-group-item"><%= room.max_guests %></dd>
    <dt>Valor da diária:</dt>
    <dd class="list-group-item"><%= number_to_currency room.price, unit: "R$", separator: ",", delimiter: "." %></dd>
    <dt>Comodidades:</dt>
    <dd class="list-group-item">
      <ul class="ammenities">
        <li>Banheiro privativo: <%= room.bathroom ? "sim" : "não" %></li>
        <li>Varanda: <%= room.porch ? "sim" : "não" %></li>
        <li>Ar-condicionado: <%= room.air_conditioner ? "sim" : "não" %></li>
        <li>Televisão: <%= room.tv ? "sim" : "não" %></li>
        <li>Guarda-roupas: <%= room.wardrobe ? "sim" : "não" %></li>
        <li>Cofre: <%= room.safe ? "sim" : "não" %></li>
        <li>Acessibilidade: <%= room.accessibility ? "sim" : "não" %></li>
        <li>Wi-fi: <%= room.wifi ? "sim" : "não" %></li>
      </ul>
    </dd>
    <dt>Disponível para reservas:</dt>
    <dd class="list-group-item"><%= room.active? ? "sim" : "não" %></dd>
  </dl>
</section>

app/views/rooms/_room_card.html.erb
<div class="card">
  <% if room.photos.attached? %>
    <%= image_tag(room.photos.first, class: "card-img-top") %>
  <% else %>
    <img src="https://archive.org/download/placeholder-image/placeholder-image.jpg" alt="no image" class="card-img-top" width="100px">
  <% end %>
  <div class="card-body">
    <h2 class="card-title"><%= link_to room.name, room %></h2>
    <p class="card-text"><%= room.description %></p>
    <p class="card-text"><%= room.size %> m²</p>
    <p class="card-text">Hóspedes: <%= room.max_guests %></p>
    <p class="card-text">Diária: <%= number_to_currency room.price, 
        unit: "R$", separator: ",", delimiter: "." %></p>
    <p class="card-text">Situação: <%= room.active? ? "ativo" : "inativo" %></p>
  </div>
</div>

app/views/rooms/_room_form.html.erb
<section class="form">
  <%= form_with model: @room do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :size, class: "form-label" %>
      <%= f.number_field :size, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :max_guests, class: "form-label" %>
      <%= f.number_field :max_guests, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :price, class: "form-label" %>
      <%= f.number_field :price, step: 0.01, class: "form-control" %>
    </div>
    <div class="mb-3 row">
      <p>Comodidades</p>
      <div class="col-md-6">
        <div class="form-check form-switch">
          <%= f.label :bathroom, class: "form-check-label" %>
          <%= f.check_box :bathroom, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :porch, class: "form-check-label" %>
          <%= f.check_box :porch, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :air_conditioner, class: "form-label" %>
          <%= f.check_box :air_conditioner, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :tv, class: "form-check-label" %>
          <%= f.check_box :tv, class: "form-check-input" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-check form-switch">
          <%= f.label :wardrobe, class: "form-check-label" %>
          <%= f.check_box :wardrobe, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :safe, class: "form-check-label" %>
          <%= f.check_box :safe, class: "form-check-input" %>
        </div>
        <div class="form-check form-switch">
          <%= f.label :accessibility, class: "form-check-label" %>
          <%= f.check_box :accessibility, class: "form-check-input"%>
        </div>
        <div class="form-check form-switch">
          <%= f.label :wifi, class: "form-check-label" %>
          <%= f.check_box :wifi, class: "form-check-input" %>
        </div>
      </div>
    </div>
    <br>
    <div class="form-check form-switch">
      <%= f.label :active, class: "form-check-label" %>
      <%= f.check_box :active, class: "form-check-input" %>
    </div>
    <br>
    <div class="mb-3 input-group">
      <%= f.label :photos, "Fotos", class: "input-group-text" %>
      <%= f.file_field :photos, multiple: true, class: "form-control" %>
    </div>
    <div class="text-center d-grid gap-2">
      <%= f.submit "Salvar Quarto", class: "btn tn-lg btn-dark" %>
    </div>
  <% end %>

</section>

app/views/rooms/_rooms_list.html.erb
<div class="container">

  <br>

  <% if @rooms.empty? %>
    <p>Nenhum quarto cadastrado</p>
  <% end %>

  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-md-4">
        <%= render partial: "rooms/room_card", locals: { room: room } %>
      </div>
    <% end %>
  </section>
  <br>

  <div class="text-center">
    <%=link_to "Novo Quarto", new_room_path, class: "btn btn-lg btn-dark" %>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render partial: "shared/form_errors", locals: { model: @room } %>

<h1>Editar quarto</h1>

<%= render partial: "room_form" %>

<% if owner_signed_in? %>
	<%= link_to t("back_link"), my_inn_path %>
<% else %>
	<%= link_to inn_path(@room.inn) %>
<% end %>

app/views/rooms/index.html.erb
<h1>Quartos: <%= @inn.name %></h1>

<%=link_to "Novo Quarto", new_room_path %>

<% if @rooms.empty? %>
  <p>Nenhum quarto cadastrado</p>
<% end %>

<section>
  <% @rooms.each do |room| %>
    <div class="room-preview">
      <h4>Quarto</h4>
      <h2><%= link_to room.name, room %></h2>
      <p><%= room.description %></p>
      <p><%= room.size %> m²</p>
      <p>Hóspedes: <%= room.max_guests %></p>
      <p>Diária: <%= number_to_currency room.price, 
        unit: "R$", separator: ",", delimiter: "." %></p>
      <p>Situação: <%= room.active? ? "ativo" : "inativo" %></p>
    </div>
  <% end %>
</section>

app/views/rooms/new.html.erb
<%= render partial: "shared/form_errors", locals: { model: @room }%>

<h1>Novo Quarto</h1>

<%= render partial: "room_form"%>

app/views/rooms/show.html.erb
<section class="details">
  <%= render @room %>

  <% if owner_signed_in? && @room.inn.owner == current_owner %>
    <div>
      <%= link_to "Editar Quarto", edit_room_path(@room), class: "btn btn-lg btn-dark" %>
    </div>
  <% end %>

  <% unless owner_signed_in? %>
    <%= button_to "Reservar", new_room_booking_path(@room), method: :get, class: "btn btn-lg btn-dark" %>
  <% end %>

  <br>
  <br>

  <div>
    <h3>Preços Sazonais</h3>
    <% if @seasonal_prices.empty? %>
      <p>Nenhum Preço Sazonal Cadastrado</p>
    <% end %>

    <div id="seasonal-prices">
      <% @seasonal_prices.each do |price| %>
          <div class="card w-50 mb-3">
            <div class="card-body">
              <%= link_to price.date_pretty_print, edit_seasonal_price_path(price) %> | 
              <%= number_to_currency price.price, unit: "R$", separator: ",", delimiter: "." %>
            </div>
        </div>
      <% end %>
    </div>

    <% if owner_signed_in? && @room.inn.owner == current_owner %>
      <%= link_to "Novo Preço Sazonal", new_room_seasonal_price_path(@room), class: "btn btn-lg btn-dark" %>
    <% end %>
  </div>

  <br>

  <% if owner_signed_in? %>
    <%= link_to "Voltar", my_inn_path, class: "btn btn-lg btn-outline-dark" %>
  <% else %>
    <%= link_to "Voltar", inn_path(@room.inn), class: "btn btn-lg btn-outline-dark" %>
  <% end %>
</section>