config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: "owners", controllers: {
    sesions: "owners/sessions",
    registrations: "owners/registrations",
    passwords: "owners/passwords",
    confirmations: "owners/confirmations",
    unlocks: "owner/unlocks"
  }

  devise_for :users, path: "users", controllers: {
    sesions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  root "home#index"
  get "logins", to: "home#logins"
  get "minha_pousada", to: "inns#my_inn", as: "my_inn"
  get "minhas_reservas", to: "bookings#my_bookings", as: "my_bookings"

  resources :addresses, only: [:new, :create]

  resources :inns, only: [:new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    get "search", on: :collection
    get "city_search", on: :collection
    get "advanced_search", on: :collection
    delete "remove_photo", on: :member

    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:index, :new, :create, :show, :edit, :update] do
    patch "change_status", on: :member
    delete "remove_photo", on: :member

    resources :seasonal_prices, only: [:new, :create]

    resources :bookings, only: [:new, :create] do
      get "confirmation", on: :collection
      post "cancel", on: :member
      post "check_in", on: :member
      post "check_out", on: :member
    end
  end

  resources :bookings, only: [:index, :show] do
    get "active", on: :collection

    resources :reviews, only: [:new, :create] do
      post "answer", on: :member
    end
  end

  resources :seasonal_prices, only: [:show, :edit, :update, :destroy]

  resources :reviews, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :inns, only: [:index, :show] do
        resources :rooms, only: [:index]
        get "cities", on: :collection
      end

      resources :bookings, only: [] do
        get "pre-booking", on: :collection
      end
    end
  end
end

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid justify-content-center">
    <%= link_to "Pousadaria", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mx-auto">

        <form id="search-bar" action="/inns/search" class="d-flex" role="search" accept-charset="UTF-8"   method="get">
          <input id="query" name="query" class="form-control me-2" type="search" placeholder="Nome, cidade ou bairro" aria-label="Search">
          <input class="btn btn-sm btn-dark" type="submit" name="commit" value="Buscar">
        </form>

        <li class="nav-item">
            <%= link_to t("advanced_search"), advanced_search_inns_path, class: "nav-link active" %>
        </li>

        <% if owner_signed_in? %>
          <li class="nav-item">
              <a href="" class="nav-link disabled" style="color: rgb(235, 235, 235);"><%= current_owner.email %></a>
          </li>
          <li class="nav-item">
            <%= link_to t("my_inn"), my_inn_path, class: "nav-link active" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to Booking.model_name.human(count: 2), bookings_path, class: "dropdown-item" %></li>
              <li><%= link_to t("active_bookings"), active_bookings_path, class: "dropdown-item" %></li>
              <li><%= link_to Review.model_name.human(count: 2), reviews_path, class: "dropdown-item" %></li>
              <li><%= button_to t("exit"), destroy_owner_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        
        <% elsif user_signed_in? %>
          <li class="nav-item">
              <a href="" class="nav-link disabled" style="color: rgb(235, 235, 235);"><%= current_user.email %></a>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("my_bookings"), my_bookings_path, class: "dropdown-item" %></li>
            <li><%= button_to t("exit"), destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>

        <% else %>
          <li class="nav-item">
            <%= link_to t("enter"), logins_path, class: "nav-link active" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_search_bar.html.erb
  <%= form_with(url: search_inns_path, method: :get) do |f| %>
    <%= f.label :query, t("search_inn") %>
    <%= f.text_field :query, placeholder: t("search_bar_placeholder") %>
    <%= f.submit t("search_button") %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pousadaria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>

  <body>

    <header>
      <nav id="navigation-bar">
        <%= render partial: "layouts/navigation_bar" %>
      </nav>
    </header>

      <% if flash[:notice] %>
        <div class="alert alert-primary text-center">
          <%= notice %>
        </div>
      <% end %>

      <% if flash[:alert]%>
        <div class="alert alert-danger text-center">
          <%= alert %>
        </div>
      <% end %>

    <%= yield %>

    <footer class="mt-5">
      <hr>
      <div class="mb-3 text-center">
        <small>Frederico Mozzato - 2023</small>
      </div>
    </footer>
  </body>
</html>